name: amen_app
description: A Bible study app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  animate_do: ^3.3.3
  provider: ^6.1.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/profiles/user1.png.jpg
    - assets/images/profiles/user2.png.jpg
    - assets/images/profiles/user3.png.jpg
    - assets/images/profiles/user4.png.jpg
    - assets/images/profiles/user5.png.jpg
    - assets/images/profiles/group1.png.jpg
    - assets/images/profiles/group2.png.jpg
    - assets/images/profiles/group3.png.jpg
    - assets/images/profiles/group4.png.jpg
    - assets/images/profiles/group5.png.jpg