name: amen_app
description: A Bible study app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  fl_chart: ^0.66.2
  provider: ^6.1.5
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  flutter_svg: ^2.2.0
  flutter_native_splash: ^2.4.6
  image_picker: ^1.1.1
  pusher_channels_flutter: ^2.2.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  sqflite: ^2.4.2
  open_file: ^3.5.10
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/books/
    - assets/images/profiles/
    - assets/amen_app_icon.svg
    - assets/amen_app_icon.png
    - assets/biblestudy3.jpeg
    - assets/icons/new_icon/bible_study_circle.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/biblestudy3.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/biblestudy3.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/biblestudy3.jpeg"
    background_color: "#FFFFFF"
    theme_color: "#2B4C7E"

flutter_native_splash:
  color: "#8c6d46"
  background_image: "assets/biblestudy3.jpeg"
  image: "assets/biblestudy3.jpeg"
  image_dark: "assets/biblestudy3.jpeg"
  branding: null
  branding_dark: null

  android_12:
    icon_background_color: "#8c6d46"
    image: "assets/biblestudy3.jpeg"
    icon_background_color_dark: "#5d4630"
    image_dark: "assets/biblestudy3.jpeg"

  web: false
  fullscreen: true
